### ISSUE TITLE
Participants page error when use both method to add participant

### ISSUE THREAD

**Issue by yuanchen233** [cph-cachet/carp-portal#2]
There are two method for add participant: via email or generate anonymous participants.
If both method are used in the same study to add participants, the page is errored out.

<img width="1083" alt="Screenshot 2024-07-31 at 15 24 52" src="https://github.com/user-attachments/assets/d5c6c59c-015a-4100-9b18-29e6e1a6a707">

**Comment by jakdan99** [comment]
Fixed in #3
