### ISSUE TITLE
The name of the protocol on the protocol page is wrong

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-portal#35]
On the protocol page, in the top box, the name and version of the protocol is wrong. In the below example is says "Study protocol v1.0" even though the name of the protocol is "CATCH Protocol v. 2.0":

<img width="630" alt="image" src="https://github.com/user-attachments/assets/694b1ae2-2952-4475-96ab-3588ef17f9ad">

**Comment by yuanchen233** [comment]
They refers to different things as I understand. The top box is the carp notion of `protocolVersion` under `protocolService`, it's added when you click `Add Version`. The bottom one is the name, so the `v. 2.0` here is part of the name.. maybe we should rename one of them.

**Comment by bardram** [comment]
Then replace the text "Study Protocol" with a label saying "Current Version:" and then the `protocolVersion`.
